<?xml version="1.0" encoding="utf-8" standalone="no"?>
<test-run id="2" name="PimsSupport.dll" fullname="C:\Users\OTurkakin\source\Workspaces\FRAMEWORK\Project_XYZ\PimsSupport\bin\Debug\PimsSupport.dll" testcasecount="24" result="Failed" total="24" passed="0" failed="24" inconclusive="0" skipped="0" asserts="0" engine-version="3.10.0.0" clr-version="4.0.30319.42000" start-time="2021-06-06 12:57:54Z" end-time="2021-06-06 13:09:34Z" duration="700.089103">
  <command-line><![CDATA["C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\Extensions\TestPlatform\Extensions\..//testhost.x86.exe"  --port 55714 --endpoint 127.0.0.1:055714 --role client --parentprocessid 24388 --datacollectionport 0 --telemetryoptedin true]]></command-line>
  <filter>
    <or>
      <test>PimsSupport.TESTS.LoginTest_Negative("chrome").ValidateLogin_InvalidPasswords_DD2("userName.2","password2")</test>
      <test>PimsSupport.TESTS.LoginTest_Negative("chrome").ValidateLogin_InvalidPasswords_DD2("userName4","password4.")</test>
      <test>PimsSupport.TESTS.LoginTest_Negative("chrome").ValidateLogin_InvalidPasswords_DD2("userName1..","password1")</test>
      <test>PimsSupport.TESTS.LoginTest_Negative("chrome").ValidateLogin_InvalidPasswords_DD2("userName.3.","password.3.")</test>
      <test>PimsSupport.TESTS.LoginTest_Negative("chrome").ValidateLogin_InvalidUsernames_DD1("userName4.","password44")</test>
      <test>PimsSupport.TESTS.LoginTest_Negative("chrome").ValidateLogin_InvalidUsernames_DD1("userName.2","password2")</test>
      <test>PimsSupport.TESTS.LoginTest_Negative("chrome").ValidateLogin_InvalidUsernames_DD1("userName.3.","password3.")</test>
      <test>PimsSupport.TESTS.LoginTest_Negative("chrome").ValidateLogin_InvalidUsernames_DD1("userName1","password1.")</test>
      <test>PimsSupport.TESTS.LoginTest_Negative("chrome").ValidateLogin_InvalidUsernames_DD1("....","....")</test>
      <test>PimsSupport.TESTS.LoginTest_Negative("chrome").ValidateLogin_NoPassword</test>
      <test>PimsSupport.TESTS.LoginTest_Negative("chrome").ValidateLogin_NoUsername</test>
      <test>PimsSupport.TESTS.LoginTest_Positive("chrome").ValidateLoginUser1</test>
      <test>PimsSupport.TESTS.LoginTest_Positive("chrome").ValidateLoginUser2</test>
      <test>PimsSupport.TESTS.LoginTest_Positive("chrome").ValidateLoginUser_ExcelSource_DataDriven4</test>
      <test>PimsSupport.TESTS.LoginTest_Positive("chrome").ValidateLoginUser_xmlSource_DataDriven6</test>
      <test>PimsSupport.TESTS.LoginTest_Positive("chrome").ValidateLoginUsers_ExcelSource_DataDriven5</test>
      <test>PimsSupport.TESTS.LoginTest_Positive("chrome").ValidateLoginUsers_TestCaseSourceAtributeClass_DataDriven3("userName1","password1")</test>
      <test>PimsSupport.TESTS.LoginTest_Positive("chrome").ValidateLoginUsers_TestCaseSourceAtributeClass_DataDriven3("userName3","password3")</test>
      <test>PimsSupport.TESTS.LoginTest_Positive("chrome").ValidateLoginUsers_TestCaseSourceAtributeClass_DataDriven3("userName2","password2")</test>
      <test>PimsSupport.TESTS.LoginTest_Positive("chrome").ValidateLoginUsers_TestCaseSourceAtributeClass_DataDriven3("userName4","password4")</test>
      <test>PimsSupport.TESTS.LoginTest_Positive("chrome").ValidateLoginUsers_TestCaseSourceCollection_DataDriven2("userName1","password1")</test>
      <test>PimsSupport.TESTS.LoginTest_Positive("chrome").ValidateLoginUsers_TestCase_DataDriven1("userName4","password4")</test>
      <test>PimsSupport.TESTS.RelationshipsTest("chrome").Relationships_708A</test>
      <test>PimsSupport.TESTS.RelationshipsTest("chrome").Relationships_742</test>
    </or>
  </filter>
  <test-suite type="Assembly" id="0-1033" name="PimsSupport.dll" fullname="C:\Users\OTurkakin\source\Workspaces\FRAMEWORK\Project_XYZ\PimsSupport\bin\Debug\PimsSupport.dll" runstate="Runnable" testcasecount="24" result="Failed" site="Child" start-time="2021-06-06 12:57:54Z" end-time="2021-06-06 13:09:34Z" duration="700.015774" total="24" passed="0" failed="24" warnings="0" inconclusive="0" skipped="0" asserts="0">
    <environment framework-version="3.12.0.0" clr-version="4.0.30319.42000" os-version="Microsoft Windows NT 10.0.18363.0" platform="Win32NT" cwd="C:\Users\OTurkakin\AppData\Local\Temp" machine-name="LPF22YXWQ-1123" user="oturkakin" user-domain="ELDREDGE_A" culture="en-US" uiculture="en-US" os-architecture="x86" />
    <settings>
      <setting name="SynchronousEvents" value="False" />
      <setting name="InternalTraceLevel" value="Off" />
      <setting name="RandomSeed" value="823065780" />
      <setting name="TestParametersDictionary" value="[webAppUrl, https://www.amazon.com/], [IsRemote, False]">
        <item key="webAppUrl" value="https://www.amazon.com/" />
        <item key="IsRemote" value="False" />
      </setting>
      <setting name="TestParameters" value="webAppUrl=https://www.amazon.com/;IsRemote=False" />
      <setting name="ProcessModel" value="InProcess" />
      <setting name="DomainUsage" value="Single" />
      <setting name="DefaultTestNamePattern" value="{m}{a}" />
      <setting name="WorkDirectory" value="C:\Users\OTurkakin\source\Workspaces\FRAMEWORK\Project_XYZ\PimsSupport\bin\Debug" />
      <setting name="ImageRuntimeVersion" value="4.0.30319" />
      <setting name="ImageTargetFrameworkName" value=".NETFramework,Version=v4.6.1" />
      <setting name="ImageRequiresX86" value="False" />
      <setting name="ImageRequiresDefaultAppDomainAssemblyResolver" value="False" />
      <setting name="RuntimeFramework" value="net-4.0" />
      <setting name="NumberOfTestWorkers" value="8" />
    </settings>
    <properties>
      <property name="_PID" value="16772" />
      <property name="_APPDOMAIN" value="domain-77068f79-PimsSupport.dll" />
    </properties>
    <failure>
      <message><![CDATA[One or more child tests had errors]]></message>
    </failure>
    <test-suite type="TestSuite" id="0-1034" name="PimsSupport" fullname="PimsSupport" runstate="Runnable" testcasecount="24" result="Failed" site="Child" start-time="2021-06-06 12:57:54Z" end-time="2021-06-06 13:09:34Z" duration="699.989992" total="24" passed="0" failed="24" warnings="0" inconclusive="0" skipped="0" asserts="0">
      <failure>
        <message><![CDATA[One or more child tests had errors]]></message>
      </failure>
      <test-suite type="TestSuite" id="0-1035" name="TESTS" fullname="PimsSupport.TESTS" runstate="Runnable" testcasecount="24" result="Failed" site="Child" start-time="2021-06-06 12:57:54Z" end-time="2021-06-06 13:09:34Z" duration="699.989158" total="24" passed="0" failed="24" warnings="0" inconclusive="0" skipped="0" asserts="0">
        <failure>
          <message><![CDATA[One or more child tests had errors]]></message>
        </failure>
        <test-suite type="TestFixture" id="0-1000" name="LoginTest_Negative(&quot;chrome&quot;)" fullname="PimsSupport.TESTS.LoginTest_Negative(&quot;chrome&quot;)" classname="PimsSupport.TESTS.LoginTest_Negative" runstate="Runnable" testcasecount="11" result="Failed" site="Child" start-time="2021-06-06 12:57:54Z" end-time="2021-06-06 13:03:34Z" duration="339.884878" total="11" passed="0" failed="11" warnings="0" inconclusive="0" skipped="0" asserts="0">
          <failure>
            <message><![CDATA[One or more child tests had errors]]></message>
          </failure>
          <test-case id="0-1001" name="ValidateLogin_NoUsername" fullname="PimsSupport.TESTS.LoginTest_Negative(&quot;chrome&quot;).ValidateLogin_NoUsername" methodname="ValidateLogin_NoUsername" classname="PimsSupport.TESTS.LoginTest_Negative" runstate="Runnable" seed="2126256301" result="Failed" label="Error" start-time="2021-06-06 12:57:56Z" end-time="2021-06-06 12:58:24Z" duration="28.140420" asserts="0">
            <properties>
              <property name="Description" value="Validate Login with valid password, without user name" />
              <property name="Category" value="Regression" />
              <property name="Order" value="1" />
            </properties>
            <failure>
              <message><![CDATA[OpenQA.Selenium.Support.UI.LoadableComponentException : Exception of type 'OpenQA.Selenium.Support.UI.LoadableComponentException' was thrown.
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.]]></message>
              <stack-trace><![CDATA[   at OpenQA.Selenium.Support.UI.LoadableComponent`1.Load()
   at PimsSupport.TESTS.LoginTest_Negative.SetUp() in C:\Users\OTurkakin\source\Workspaces\FRAMEWORK\Project_XYZ\PimsSupport\TESTS\Login\LoginTest_Negative.cs:line 24
--TearDown
   at PimsSupport.TESTS.LoginTest_Negative.LogoutPimsSupport() in C:\Users\OTurkakin\source\Workspaces\FRAMEWORK\Project_XYZ\PimsSupport\TESTS\Login\LoginTest_Negative.cs:line 104]]></stack-trace>
            </failure>
          </test-case>
          <test-case id="0-1002" name="ValidateLogin_NoPassword" fullname="PimsSupport.TESTS.LoginTest_Negative(&quot;chrome&quot;).ValidateLogin_NoPassword" methodname="ValidateLogin_NoPassword" classname="PimsSupport.TESTS.LoginTest_Negative" runstate="Runnable" seed="451377553" result="Failed" label="Error" start-time="2021-06-06 12:58:24Z" end-time="2021-06-06 12:58:55Z" duration="30.833056" asserts="0">
            <properties>
              <property name="Description" value="Validate Login with valid user name, without password" />
              <property name="Category" value="Regression" />
              <property name="Order" value="2" />
            </properties>
            <failure>
              <message><![CDATA[OpenQA.Selenium.Support.UI.LoadableComponentException : Exception of type 'OpenQA.Selenium.Support.UI.LoadableComponentException' was thrown.
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.]]></message>
              <stack-trace><![CDATA[   at OpenQA.Selenium.Support.UI.LoadableComponent`1.Load()
   at PimsSupport.TESTS.LoginTest_Negative.SetUp() in C:\Users\OTurkakin\source\Workspaces\FRAMEWORK\Project_XYZ\PimsSupport\TESTS\Login\LoginTest_Negative.cs:line 24
--TearDown
   at PimsSupport.TESTS.LoginTest_Negative.LogoutPimsSupport() in C:\Users\OTurkakin\source\Workspaces\FRAMEWORK\Project_XYZ\PimsSupport\TESTS\Login\LoginTest_Negative.cs:line 104]]></stack-trace>
            </failure>
          </test-case>
          <test-suite type="ParameterizedMethod" id="0-1008" name="ValidateLogin_InvalidUsernames_DD1" fullname="PimsSupport.TESTS.LoginTest_Negative.ValidateLogin_InvalidUsernames_DD1" classname="PimsSupport.TESTS.LoginTest_Negative" runstate="Runnable" testcasecount="5" result="Failed" site="Child" start-time="2021-06-06 12:58:55Z" end-time="2021-06-06 13:01:20Z" duration="144.604525" total="5" passed="0" failed="5" warnings="0" inconclusive="0" skipped="0" asserts="0">
            <properties>
              <property name="Description" value="Validate Login with invalid user name, valid password" />
              <property name="Category" value="Regression" />
              <property name="Order" value="3" />
            </properties>
            <failure>
              <message><![CDATA[One or more child tests had errors]]></message>
            </failure>
            <test-case id="0-1003" name="ValidateLogin_InvalidUsernames_DD1(&quot;....&quot;,&quot;....&quot;)" fullname="PimsSupport.TESTS.LoginTest_Negative(&quot;chrome&quot;).ValidateLogin_InvalidUsernames_DD1(&quot;....&quot;,&quot;....&quot;)" methodname="ValidateLogin_InvalidUsernames_DD1" classname="PimsSupport.TESTS.LoginTest_Negative" runstate="Runnable" seed="1902985337" result="Failed" label="Error" start-time="2021-06-06 12:58:55Z" end-time="2021-06-06 12:59:24Z" duration="29.420220" asserts="0">
              <failure>
                <message><![CDATA[OpenQA.Selenium.Support.UI.LoadableComponentException : Exception of type 'OpenQA.Selenium.Support.UI.LoadableComponentException' was thrown.
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.]]></message>
                <stack-trace><![CDATA[   at OpenQA.Selenium.Support.UI.LoadableComponent`1.Load()
   at PimsSupport.TESTS.LoginTest_Negative.SetUp() in C:\Users\OTurkakin\source\Workspaces\FRAMEWORK\Project_XYZ\PimsSupport\TESTS\Login\LoginTest_Negative.cs:line 24
--TearDown
   at PimsSupport.TESTS.LoginTest_Negative.LogoutPimsSupport() in C:\Users\OTurkakin\source\Workspaces\FRAMEWORK\Project_XYZ\PimsSupport\TESTS\Login\LoginTest_Negative.cs:line 104]]></stack-trace>
              </failure>
            </test-case>
            <test-case id="0-1004" name="ValidateLogin_InvalidUsernames_DD1(&quot;userName1&quot;,&quot;password1.&quot;)" fullname="PimsSupport.TESTS.LoginTest_Negative(&quot;chrome&quot;).ValidateLogin_InvalidUsernames_DD1(&quot;userName1&quot;,&quot;password1.&quot;)" methodname="ValidateLogin_InvalidUsernames_DD1" classname="PimsSupport.TESTS.LoginTest_Negative" runstate="Runnable" seed="910776860" result="Failed" label="Error" start-time="2021-06-06 12:59:24Z" end-time="2021-06-06 12:59:55Z" duration="30.856798" asserts="0">
              <failure>
                <message><![CDATA[OpenQA.Selenium.Support.UI.LoadableComponentException : Exception of type 'OpenQA.Selenium.Support.UI.LoadableComponentException' was thrown.
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.]]></message>
                <stack-trace><![CDATA[   at OpenQA.Selenium.Support.UI.LoadableComponent`1.Load()
   at PimsSupport.TESTS.LoginTest_Negative.SetUp() in C:\Users\OTurkakin\source\Workspaces\FRAMEWORK\Project_XYZ\PimsSupport\TESTS\Login\LoginTest_Negative.cs:line 24
--TearDown
   at PimsSupport.TESTS.LoginTest_Negative.LogoutPimsSupport() in C:\Users\OTurkakin\source\Workspaces\FRAMEWORK\Project_XYZ\PimsSupport\TESTS\Login\LoginTest_Negative.cs:line 104]]></stack-trace>
              </failure>
            </test-case>
            <test-case id="0-1005" name="ValidateLogin_InvalidUsernames_DD1(&quot;userName.2&quot;,&quot;password2&quot;)" fullname="PimsSupport.TESTS.LoginTest_Negative(&quot;chrome&quot;).ValidateLogin_InvalidUsernames_DD1(&quot;userName.2&quot;,&quot;password2&quot;)" methodname="ValidateLogin_InvalidUsernames_DD1" classname="PimsSupport.TESTS.LoginTest_Negative" runstate="Runnable" seed="2084899622" result="Failed" label="Error" start-time="2021-06-06 12:59:55Z" end-time="2021-06-06 13:00:23Z" duration="28.259646" asserts="0">
              <failure>
                <message><![CDATA[OpenQA.Selenium.Support.UI.LoadableComponentException : Exception of type 'OpenQA.Selenium.Support.UI.LoadableComponentException' was thrown.
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.]]></message>
                <stack-trace><![CDATA[   at OpenQA.Selenium.Support.UI.LoadableComponent`1.Load()
   at PimsSupport.TESTS.LoginTest_Negative.SetUp() in C:\Users\OTurkakin\source\Workspaces\FRAMEWORK\Project_XYZ\PimsSupport\TESTS\Login\LoginTest_Negative.cs:line 24
--TearDown
   at PimsSupport.TESTS.LoginTest_Negative.LogoutPimsSupport() in C:\Users\OTurkakin\source\Workspaces\FRAMEWORK\Project_XYZ\PimsSupport\TESTS\Login\LoginTest_Negative.cs:line 104]]></stack-trace>
              </failure>
            </test-case>
            <test-case id="0-1006" name="ValidateLogin_InvalidUsernames_DD1(&quot;userName.3.&quot;,&quot;password3.&quot;)" fullname="PimsSupport.TESTS.LoginTest_Negative(&quot;chrome&quot;).ValidateLogin_InvalidUsernames_DD1(&quot;userName.3.&quot;,&quot;password3.&quot;)" methodname="ValidateLogin_InvalidUsernames_DD1" classname="PimsSupport.TESTS.LoginTest_Negative" runstate="Runnable" seed="206549872" result="Failed" label="Error" start-time="2021-06-06 13:00:23Z" end-time="2021-06-06 13:00:52Z" duration="28.052623" asserts="0">
              <failure>
                <message><![CDATA[OpenQA.Selenium.Support.UI.LoadableComponentException : Exception of type 'OpenQA.Selenium.Support.UI.LoadableComponentException' was thrown.
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.]]></message>
                <stack-trace><![CDATA[   at OpenQA.Selenium.Support.UI.LoadableComponent`1.Load()
   at PimsSupport.TESTS.LoginTest_Negative.SetUp() in C:\Users\OTurkakin\source\Workspaces\FRAMEWORK\Project_XYZ\PimsSupport\TESTS\Login\LoginTest_Negative.cs:line 24
--TearDown
   at PimsSupport.TESTS.LoginTest_Negative.LogoutPimsSupport() in C:\Users\OTurkakin\source\Workspaces\FRAMEWORK\Project_XYZ\PimsSupport\TESTS\Login\LoginTest_Negative.cs:line 104]]></stack-trace>
              </failure>
            </test-case>
            <test-case id="0-1007" name="ValidateLogin_InvalidUsernames_DD1(&quot;userName4.&quot;,&quot;password44&quot;)" fullname="PimsSupport.TESTS.LoginTest_Negative(&quot;chrome&quot;).ValidateLogin_InvalidUsernames_DD1(&quot;userName4.&quot;,&quot;password44&quot;)" methodname="ValidateLogin_InvalidUsernames_DD1" classname="PimsSupport.TESTS.LoginTest_Negative" runstate="Runnable" seed="854384289" result="Failed" label="Error" start-time="2021-06-06 13:00:52Z" end-time="2021-06-06 13:01:20Z" duration="28.013391" asserts="0">
              <failure>
                <message><![CDATA[OpenQA.Selenium.Support.UI.LoadableComponentException : Exception of type 'OpenQA.Selenium.Support.UI.LoadableComponentException' was thrown.
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.]]></message>
                <stack-trace><![CDATA[   at OpenQA.Selenium.Support.UI.LoadableComponent`1.Load()
   at PimsSupport.TESTS.LoginTest_Negative.SetUp() in C:\Users\OTurkakin\source\Workspaces\FRAMEWORK\Project_XYZ\PimsSupport\TESTS\Login\LoginTest_Negative.cs:line 24
--TearDown
   at PimsSupport.TESTS.LoginTest_Negative.LogoutPimsSupport() in C:\Users\OTurkakin\source\Workspaces\FRAMEWORK\Project_XYZ\PimsSupport\TESTS\Login\LoginTest_Negative.cs:line 104]]></stack-trace>
              </failure>
            </test-case>
          </test-suite>
          <test-suite type="ParameterizedMethod" id="0-1013" name="ValidateLogin_InvalidPasswords_DD2" fullname="PimsSupport.TESTS.LoginTest_Negative.ValidateLogin_InvalidPasswords_DD2" classname="PimsSupport.TESTS.LoginTest_Negative" runstate="Runnable" testcasecount="4" result="Failed" site="Child" start-time="2021-06-06 13:01:20Z" end-time="2021-06-06 13:03:13Z" duration="113.939544" total="4" passed="0" failed="4" warnings="0" inconclusive="0" skipped="0" asserts="0">
            <properties>
              <property name="Description" value="Validate Login with invalid password and valid user name " />
              <property name="Category" value="Regression" />
              <property name="Order" value="4" />
            </properties>
            <failure>
              <message><![CDATA[One or more child tests had errors]]></message>
            </failure>
            <test-case id="0-1009" name="ValidateLogin_InvalidPasswords_DD2(&quot;userName1..&quot;,&quot;password1&quot;)" fullname="PimsSupport.TESTS.LoginTest_Negative(&quot;chrome&quot;).ValidateLogin_InvalidPasswords_DD2(&quot;userName1..&quot;,&quot;password1&quot;)" methodname="ValidateLogin_InvalidPasswords_DD2" classname="PimsSupport.TESTS.LoginTest_Negative" runstate="Runnable" seed="1371396011" result="Failed" label="Error" start-time="2021-06-06 13:01:20Z" end-time="2021-06-06 13:01:47Z" duration="27.391015" asserts="0">
              <failure>
                <message><![CDATA[OpenQA.Selenium.Support.UI.LoadableComponentException : Exception of type 'OpenQA.Selenium.Support.UI.LoadableComponentException' was thrown.
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.]]></message>
                <stack-trace><![CDATA[   at OpenQA.Selenium.Support.UI.LoadableComponent`1.Load()
   at PimsSupport.TESTS.LoginTest_Negative.SetUp() in C:\Users\OTurkakin\source\Workspaces\FRAMEWORK\Project_XYZ\PimsSupport\TESTS\Login\LoginTest_Negative.cs:line 24
--TearDown
   at PimsSupport.TESTS.LoginTest_Negative.LogoutPimsSupport() in C:\Users\OTurkakin\source\Workspaces\FRAMEWORK\Project_XYZ\PimsSupport\TESTS\Login\LoginTest_Negative.cs:line 104]]></stack-trace>
              </failure>
            </test-case>
            <test-case id="0-1010" name="ValidateLogin_InvalidPasswords_DD2(&quot;userName.2&quot;,&quot;password2&quot;)" fullname="PimsSupport.TESTS.LoginTest_Negative(&quot;chrome&quot;).ValidateLogin_InvalidPasswords_DD2(&quot;userName.2&quot;,&quot;password2&quot;)" methodname="ValidateLogin_InvalidPasswords_DD2" classname="PimsSupport.TESTS.LoginTest_Negative" runstate="Runnable" seed="301282383" result="Failed" label="Error" start-time="2021-06-06 13:01:47Z" end-time="2021-06-06 13:02:15Z" duration="28.325277" asserts="0">
              <failure>
                <message><![CDATA[OpenQA.Selenium.Support.UI.LoadableComponentException : Exception of type 'OpenQA.Selenium.Support.UI.LoadableComponentException' was thrown.
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.]]></message>
                <stack-trace><![CDATA[   at OpenQA.Selenium.Support.UI.LoadableComponent`1.Load()
   at PimsSupport.TESTS.LoginTest_Negative.SetUp() in C:\Users\OTurkakin\source\Workspaces\FRAMEWORK\Project_XYZ\PimsSupport\TESTS\Login\LoginTest_Negative.cs:line 24
--TearDown
   at PimsSupport.TESTS.LoginTest_Negative.LogoutPimsSupport() in C:\Users\OTurkakin\source\Workspaces\FRAMEWORK\Project_XYZ\PimsSupport\TESTS\Login\LoginTest_Negative.cs:line 104]]></stack-trace>
              </failure>
            </test-case>
            <test-case id="0-1011" name="ValidateLogin_InvalidPasswords_DD2(&quot;userName.3.&quot;,&quot;password.3.&quot;)" fullname="PimsSupport.TESTS.LoginTest_Negative(&quot;chrome&quot;).ValidateLogin_InvalidPasswords_DD2(&quot;userName.3.&quot;,&quot;password.3.&quot;)" methodname="ValidateLogin_InvalidPasswords_DD2" classname="PimsSupport.TESTS.LoginTest_Negative" runstate="Runnable" seed="1877980932" result="Failed" label="Error" start-time="2021-06-06 13:02:15Z" end-time="2021-06-06 13:02:46Z" duration="30.443564" asserts="0">
              <failure>
                <message><![CDATA[OpenQA.Selenium.Support.UI.LoadableComponentException : Exception of type 'OpenQA.Selenium.Support.UI.LoadableComponentException' was thrown.
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.]]></message>
                <stack-trace><![CDATA[   at OpenQA.Selenium.Support.UI.LoadableComponent`1.Load()
   at PimsSupport.TESTS.LoginTest_Negative.SetUp() in C:\Users\OTurkakin\source\Workspaces\FRAMEWORK\Project_XYZ\PimsSupport\TESTS\Login\LoginTest_Negative.cs:line 24
--TearDown
   at PimsSupport.TESTS.LoginTest_Negative.LogoutPimsSupport() in C:\Users\OTurkakin\source\Workspaces\FRAMEWORK\Project_XYZ\PimsSupport\TESTS\Login\LoginTest_Negative.cs:line 104]]></stack-trace>
              </failure>
            </test-case>
            <test-case id="0-1012" name="ValidateLogin_InvalidPasswords_DD2(&quot;userName4&quot;,&quot;password4.&quot;)" fullname="PimsSupport.TESTS.LoginTest_Negative(&quot;chrome&quot;).ValidateLogin_InvalidPasswords_DD2(&quot;userName4&quot;,&quot;password4.&quot;)" methodname="ValidateLogin_InvalidPasswords_DD2" classname="PimsSupport.TESTS.LoginTest_Negative" runstate="Runnable" seed="273680797" result="Failed" label="Error" start-time="2021-06-06 13:02:46Z" end-time="2021-06-06 13:03:13Z" duration="27.779484" asserts="0">
              <failure>
                <message><![CDATA[OpenQA.Selenium.Support.UI.LoadableComponentException : Exception of type 'OpenQA.Selenium.Support.UI.LoadableComponentException' was thrown.
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.]]></message>
                <stack-trace><![CDATA[   at OpenQA.Selenium.Support.UI.LoadableComponent`1.Load()
   at PimsSupport.TESTS.LoginTest_Negative.SetUp() in C:\Users\OTurkakin\source\Workspaces\FRAMEWORK\Project_XYZ\PimsSupport\TESTS\Login\LoginTest_Negative.cs:line 24
--TearDown
   at PimsSupport.TESTS.LoginTest_Negative.LogoutPimsSupport() in C:\Users\OTurkakin\source\Workspaces\FRAMEWORK\Project_XYZ\PimsSupport\TESTS\Login\LoginTest_Negative.cs:line 104]]></stack-trace>
              </failure>
            </test-case>
          </test-suite>
        </test-suite>
        <test-suite type="TestFixture" id="0-1014" name="LoginTest_Positive(&quot;chrome&quot;)" fullname="PimsSupport.TESTS.LoginTest_Positive(&quot;chrome&quot;)" classname="PimsSupport.TESTS.LoginTest_Positive" runstate="Runnable" testcasecount="11" result="Failed" site="Child" start-time="2021-06-06 13:03:34Z" end-time="2021-06-06 13:08:32Z" duration="298.583209" total="11" passed="0" failed="11" warnings="0" inconclusive="0" skipped="0" asserts="0">
          <properties>
            <property name="ParallelScope" value="Self" />
          </properties>
          <failure>
            <message><![CDATA[One or more child tests had errors]]></message>
          </failure>
          <test-case id="0-1015" name="ValidateLoginUser1" fullname="PimsSupport.TESTS.LoginTest_Positive(&quot;chrome&quot;).ValidateLoginUser1" methodname="ValidateLoginUser1" classname="PimsSupport.TESTS.LoginTest_Positive" runstate="Runnable" seed="240899251" result="Failed" label="Error" start-time="2021-06-06 13:03:34Z" end-time="2021-06-06 13:04:02Z" duration="28.154969" asserts="0">
            <properties>
              <property name="Description" value="Login as a USER1 and validate landingPage URL is loded" />
              <property name="Category" value="Regression" />
              <property name="Category" value="SmokeTesting" />
              <property name="Order" value="1" />
            </properties>
            <failure>
              <message><![CDATA[OpenQA.Selenium.Support.UI.LoadableComponentException : Exception of type 'OpenQA.Selenium.Support.UI.LoadableComponentException' was thrown.
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.]]></message>
              <stack-trace><![CDATA[   at OpenQA.Selenium.Support.UI.LoadableComponent`1.Load()
   at PimsSupport.TESTS.LoginTest_Positive.SetUp() in C:\Users\OTurkakin\source\Workspaces\FRAMEWORK\Project_XYZ\PimsSupport\TESTS\Login\LoginTest_Positive.cs:line 29
--TearDown
   at PimsSupport.TESTS.LoginTest_Positive.Logout() in C:\Users\OTurkakin\source\Workspaces\FRAMEWORK\Project_XYZ\PimsSupport\TESTS\Login\LoginTest_Positive.cs:line 157]]></stack-trace>
            </failure>
          </test-case>
          <test-case id="0-1016" name="ValidateLoginUser2" fullname="PimsSupport.TESTS.LoginTest_Positive(&quot;chrome&quot;).ValidateLoginUser2" methodname="ValidateLoginUser2" classname="PimsSupport.TESTS.LoginTest_Positive" runstate="Runnable" seed="621050545" result="Failed" label="Error" start-time="2021-06-06 13:04:02Z" end-time="2021-06-06 13:04:30Z" duration="28.421299" asserts="0">
            <properties>
              <property name="Description" value="Login as a USER2 and validate landingPage URL is loded" />
              <property name="Category" value="Regression" />
              <property name="Category" value="SmokeTesting" />
              <property name="Order" value="2" />
            </properties>
            <failure>
              <message><![CDATA[OpenQA.Selenium.Support.UI.LoadableComponentException : Exception of type 'OpenQA.Selenium.Support.UI.LoadableComponentException' was thrown.
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.]]></message>
              <stack-trace><![CDATA[   at OpenQA.Selenium.Support.UI.LoadableComponent`1.Load()
   at PimsSupport.TESTS.LoginTest_Positive.SetUp() in C:\Users\OTurkakin\source\Workspaces\FRAMEWORK\Project_XYZ\PimsSupport\TESTS\Login\LoginTest_Positive.cs:line 29
--TearDown
   at PimsSupport.TESTS.LoginTest_Positive.Logout() in C:\Users\OTurkakin\source\Workspaces\FRAMEWORK\Project_XYZ\PimsSupport\TESTS\Login\LoginTest_Positive.cs:line 157]]></stack-trace>
            </failure>
          </test-case>
          <test-suite type="ParameterizedMethod" id="0-1020" name="ValidateLoginUsers_TestCaseSourceCollection_DataDriven2" fullname="PimsSupport.TESTS.LoginTest_Positive.ValidateLoginUsers_TestCaseSourceCollection_DataDriven2" classname="PimsSupport.TESTS.LoginTest_Positive" runstate="Runnable" testcasecount="1" result="Failed" site="Child" start-time="2021-06-06 13:04:30Z" end-time="2021-06-06 13:04:58Z" duration="27.354498" total="1" passed="0" failed="1" warnings="0" inconclusive="0" skipped="0" asserts="0">
            <properties>
              <property name="Description" value="Login with valid credentials and validate landingPage URL is exist" />
              <property name="Category" value="Regression" />
              <property name="Category" value="SmokeTesting" />
              <property name="Order" value="3" />
            </properties>
            <failure>
              <message><![CDATA[One or more child tests had errors]]></message>
            </failure>
            <test-case id="0-1019" name="ValidateLoginUsers_TestCaseSourceCollection_DataDriven2(&quot;userName1&quot;,&quot;password1&quot;)" fullname="PimsSupport.TESTS.LoginTest_Positive(&quot;chrome&quot;).ValidateLoginUsers_TestCaseSourceCollection_DataDriven2(&quot;userName1&quot;,&quot;password1&quot;)" methodname="ValidateLoginUsers_TestCaseSourceCollection_DataDriven2" classname="PimsSupport.TESTS.LoginTest_Positive" runstate="Runnable" seed="1628113693" result="Failed" label="Error" start-time="2021-06-06 13:04:30Z" end-time="2021-06-06 13:04:58Z" duration="27.354392" asserts="0">
              <failure>
                <message><![CDATA[OpenQA.Selenium.Support.UI.LoadableComponentException : Exception of type 'OpenQA.Selenium.Support.UI.LoadableComponentException' was thrown.
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.]]></message>
                <stack-trace><![CDATA[   at OpenQA.Selenium.Support.UI.LoadableComponent`1.Load()
   at PimsSupport.TESTS.LoginTest_Positive.SetUp() in C:\Users\OTurkakin\source\Workspaces\FRAMEWORK\Project_XYZ\PimsSupport\TESTS\Login\LoginTest_Positive.cs:line 29
--TearDown
   at PimsSupport.TESTS.LoginTest_Positive.Logout() in C:\Users\OTurkakin\source\Workspaces\FRAMEWORK\Project_XYZ\PimsSupport\TESTS\Login\LoginTest_Positive.cs:line 157]]></stack-trace>
              </failure>
            </test-case>
          </test-suite>
          <test-suite type="ParameterizedMethod" id="0-1018" name="ValidateLoginUsers_TestCase_DataDriven1" fullname="PimsSupport.TESTS.LoginTest_Positive.ValidateLoginUsers_TestCase_DataDriven1" classname="PimsSupport.TESTS.LoginTest_Positive" runstate="Runnable" testcasecount="1" result="Failed" site="Child" start-time="2021-06-06 13:04:58Z" end-time="2021-06-06 13:05:28Z" duration="29.795863" total="1" passed="0" failed="1" warnings="0" inconclusive="0" skipped="0" asserts="0">
            <properties>
              <property name="Description" value="Login with valid credentials and validate landingPage URL is loded" />
              <property name="Category" value="SmokeTesting" />
              <property name="Order" value="3" />
            </properties>
            <failure>
              <message><![CDATA[One or more child tests had errors]]></message>
            </failure>
            <test-case id="0-1017" name="ValidateLoginUsers_TestCase_DataDriven1(&quot;userName4&quot;,&quot;password4&quot;)" fullname="PimsSupport.TESTS.LoginTest_Positive(&quot;chrome&quot;).ValidateLoginUsers_TestCase_DataDriven1(&quot;userName4&quot;,&quot;password4&quot;)" methodname="ValidateLoginUsers_TestCase_DataDriven1" classname="PimsSupport.TESTS.LoginTest_Positive" runstate="Runnable" seed="726478386" result="Failed" label="Error" start-time="2021-06-06 13:04:58Z" end-time="2021-06-06 13:05:28Z" duration="29.795777" asserts="0">
              <failure>
                <message><![CDATA[OpenQA.Selenium.Support.UI.LoadableComponentException : Exception of type 'OpenQA.Selenium.Support.UI.LoadableComponentException' was thrown.
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.]]></message>
                <stack-trace><![CDATA[   at OpenQA.Selenium.Support.UI.LoadableComponent`1.Load()
   at PimsSupport.TESTS.LoginTest_Positive.SetUp() in C:\Users\OTurkakin\source\Workspaces\FRAMEWORK\Project_XYZ\PimsSupport\TESTS\Login\LoginTest_Positive.cs:line 29
--TearDown
   at PimsSupport.TESTS.LoginTest_Positive.Logout() in C:\Users\OTurkakin\source\Workspaces\FRAMEWORK\Project_XYZ\PimsSupport\TESTS\Login\LoginTest_Positive.cs:line 157]]></stack-trace>
              </failure>
            </test-case>
          </test-suite>
          <test-suite type="ParameterizedMethod" id="0-1025" name="ValidateLoginUsers_TestCaseSourceAtributeClass_DataDriven3" fullname="PimsSupport.TESTS.LoginTest_Positive.ValidateLoginUsers_TestCaseSourceAtributeClass_DataDriven3" classname="PimsSupport.TESTS.LoginTest_Positive" runstate="Runnable" testcasecount="4" result="Failed" site="Child" start-time="2021-06-06 13:05:28Z" end-time="2021-06-06 13:07:27Z" duration="119.850607" total="4" passed="0" failed="4" warnings="0" inconclusive="0" skipped="0" asserts="0">
            <properties>
              <property name="Description" value="Login validation using DataManager source file " />
              <property name="Category" value="Regression" />
              <property name="Category" value="SmokeTesting" />
              <property name="Order" value="4" />
            </properties>
            <failure>
              <message><![CDATA[One or more child tests had errors]]></message>
            </failure>
            <test-case id="0-1021" name="ValidateLoginUsers_TestCaseSourceAtributeClass_DataDriven3(&quot;userName1&quot;,&quot;password1&quot;)" fullname="PimsSupport.TESTS.LoginTest_Positive(&quot;chrome&quot;).ValidateLoginUsers_TestCaseSourceAtributeClass_DataDriven3(&quot;userName1&quot;,&quot;password1&quot;)" methodname="ValidateLoginUsers_TestCaseSourceAtributeClass_DataDriven3" classname="PimsSupport.TESTS.LoginTest_Positive" runstate="Runnable" seed="1970376917" result="Failed" label="Error" start-time="2021-06-06 13:05:28Z" end-time="2021-06-06 13:05:59Z" duration="31.667790" asserts="0">
              <failure>
                <message><![CDATA[OpenQA.Selenium.Support.UI.LoadableComponentException : Exception of type 'OpenQA.Selenium.Support.UI.LoadableComponentException' was thrown.
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.]]></message>
                <stack-trace><![CDATA[   at OpenQA.Selenium.Support.UI.LoadableComponent`1.Load()
   at PimsSupport.TESTS.LoginTest_Positive.SetUp() in C:\Users\OTurkakin\source\Workspaces\FRAMEWORK\Project_XYZ\PimsSupport\TESTS\Login\LoginTest_Positive.cs:line 29
--TearDown
   at PimsSupport.TESTS.LoginTest_Positive.Logout() in C:\Users\OTurkakin\source\Workspaces\FRAMEWORK\Project_XYZ\PimsSupport\TESTS\Login\LoginTest_Positive.cs:line 157]]></stack-trace>
              </failure>
            </test-case>
            <test-case id="0-1022" name="ValidateLoginUsers_TestCaseSourceAtributeClass_DataDriven3(&quot;userName2&quot;,&quot;password2&quot;)" fullname="PimsSupport.TESTS.LoginTest_Positive(&quot;chrome&quot;).ValidateLoginUsers_TestCaseSourceAtributeClass_DataDriven3(&quot;userName2&quot;,&quot;password2&quot;)" methodname="ValidateLoginUsers_TestCaseSourceAtributeClass_DataDriven3" classname="PimsSupport.TESTS.LoginTest_Positive" runstate="Runnable" seed="556012745" result="Failed" label="Error" start-time="2021-06-06 13:05:59Z" end-time="2021-06-06 13:06:28Z" duration="28.873017" asserts="0">
              <failure>
                <message><![CDATA[OpenQA.Selenium.Support.UI.LoadableComponentException : Exception of type 'OpenQA.Selenium.Support.UI.LoadableComponentException' was thrown.
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.]]></message>
                <stack-trace><![CDATA[   at OpenQA.Selenium.Support.UI.LoadableComponent`1.Load()
   at PimsSupport.TESTS.LoginTest_Positive.SetUp() in C:\Users\OTurkakin\source\Workspaces\FRAMEWORK\Project_XYZ\PimsSupport\TESTS\Login\LoginTest_Positive.cs:line 29
--TearDown
   at PimsSupport.TESTS.LoginTest_Positive.Logout() in C:\Users\OTurkakin\source\Workspaces\FRAMEWORK\Project_XYZ\PimsSupport\TESTS\Login\LoginTest_Positive.cs:line 157]]></stack-trace>
              </failure>
            </test-case>
            <test-case id="0-1023" name="ValidateLoginUsers_TestCaseSourceAtributeClass_DataDriven3(&quot;userName3&quot;,&quot;password3&quot;)" fullname="PimsSupport.TESTS.LoginTest_Positive(&quot;chrome&quot;).ValidateLoginUsers_TestCaseSourceAtributeClass_DataDriven3(&quot;userName3&quot;,&quot;password3&quot;)" methodname="ValidateLoginUsers_TestCaseSourceAtributeClass_DataDriven3" classname="PimsSupport.TESTS.LoginTest_Positive" runstate="Runnable" seed="931532964" result="Failed" label="Error" start-time="2021-06-06 13:06:28Z" end-time="2021-06-06 13:06:59Z" duration="30.962861" asserts="0">
              <failure>
                <message><![CDATA[OpenQA.Selenium.Support.UI.LoadableComponentException : Exception of type 'OpenQA.Selenium.Support.UI.LoadableComponentException' was thrown.
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.]]></message>
                <stack-trace><![CDATA[   at OpenQA.Selenium.Support.UI.LoadableComponent`1.Load()
   at PimsSupport.TESTS.LoginTest_Positive.SetUp() in C:\Users\OTurkakin\source\Workspaces\FRAMEWORK\Project_XYZ\PimsSupport\TESTS\Login\LoginTest_Positive.cs:line 29
--TearDown
   at PimsSupport.TESTS.LoginTest_Positive.Logout() in C:\Users\OTurkakin\source\Workspaces\FRAMEWORK\Project_XYZ\PimsSupport\TESTS\Login\LoginTest_Positive.cs:line 157]]></stack-trace>
              </failure>
            </test-case>
            <test-case id="0-1024" name="ValidateLoginUsers_TestCaseSourceAtributeClass_DataDriven3(&quot;userName4&quot;,&quot;password4&quot;)" fullname="PimsSupport.TESTS.LoginTest_Positive(&quot;chrome&quot;).ValidateLoginUsers_TestCaseSourceAtributeClass_DataDriven3(&quot;userName4&quot;,&quot;password4&quot;)" methodname="ValidateLoginUsers_TestCaseSourceAtributeClass_DataDriven3" classname="PimsSupport.TESTS.LoginTest_Positive" runstate="Runnable" seed="1191118130" result="Failed" label="Error" start-time="2021-06-06 13:06:59Z" end-time="2021-06-06 13:07:27Z" duration="28.346618" asserts="0">
              <failure>
                <message><![CDATA[OpenQA.Selenium.Support.UI.LoadableComponentException : Exception of type 'OpenQA.Selenium.Support.UI.LoadableComponentException' was thrown.
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.]]></message>
                <stack-trace><![CDATA[   at OpenQA.Selenium.Support.UI.LoadableComponent`1.Load()
   at PimsSupport.TESTS.LoginTest_Positive.SetUp() in C:\Users\OTurkakin\source\Workspaces\FRAMEWORK\Project_XYZ\PimsSupport\TESTS\Login\LoginTest_Positive.cs:line 29
--TearDown
   at PimsSupport.TESTS.LoginTest_Positive.Logout() in C:\Users\OTurkakin\source\Workspaces\FRAMEWORK\Project_XYZ\PimsSupport\TESTS\Login\LoginTest_Positive.cs:line 157]]></stack-trace>
              </failure>
            </test-case>
          </test-suite>
          <test-case id="0-1026" name="ValidateLoginUser_ExcelSource_DataDriven4" fullname="PimsSupport.TESTS.LoginTest_Positive(&quot;chrome&quot;).ValidateLoginUser_ExcelSource_DataDriven4" methodname="ValidateLoginUser_ExcelSource_DataDriven4" classname="PimsSupport.TESTS.LoginTest_Positive" runstate="Runnable" seed="1885211406" result="Failed" label="Error" start-time="2021-06-06 13:07:27Z" end-time="2021-06-06 13:07:59Z" duration="31.430339" asserts="0">
            <properties>
              <property name="Description" value="Login validation using xml data source file for first row" />
              <property name="Category" value="Regression" />
              <property name="Category" value="SmokeTesting" />
              <property name="Order" value="5" />
            </properties>
            <failure>
              <message><![CDATA[OpenQA.Selenium.Support.UI.LoadableComponentException : Exception of type 'OpenQA.Selenium.Support.UI.LoadableComponentException' was thrown.
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.]]></message>
              <stack-trace><![CDATA[   at OpenQA.Selenium.Support.UI.LoadableComponent`1.Load()
   at PimsSupport.TESTS.LoginTest_Positive.SetUp() in C:\Users\OTurkakin\source\Workspaces\FRAMEWORK\Project_XYZ\PimsSupport\TESTS\Login\LoginTest_Positive.cs:line 29
--TearDown
   at PimsSupport.TESTS.LoginTest_Positive.Logout() in C:\Users\OTurkakin\source\Workspaces\FRAMEWORK\Project_XYZ\PimsSupport\TESTS\Login\LoginTest_Positive.cs:line 157]]></stack-trace>
            </failure>
          </test-case>
          <test-suite type="ParameterizedMethod" id="0-1028" name="ValidateLoginUsers_ExcelSource_DataDriven5" fullname="PimsSupport.TESTS.LoginTest_Positive.ValidateLoginUsers_ExcelSource_DataDriven5" classname="PimsSupport.TESTS.LoginTest_Positive" runstate="Runnable" testcasecount="1" result="Failed" site="Child" start-time="2021-06-06 13:07:59Z" end-time="2021-06-06 13:07:59Z" duration="0.000636" total="1" passed="0" failed="1" warnings="0" inconclusive="0" skipped="0" asserts="0">
            <properties>
              <property name="Description" value="Login validation using xml data source file for second row" />
              <property name="Category" value="Regression" />
              <property name="Category" value="SmokeTesting" />
              <property name="Order" value="6" />
            </properties>
            <failure>
              <message><![CDATA[One or more child tests had errors]]></message>
            </failure>
            <test-case id="0-1027" name="ValidateLoginUsers_ExcelSource_DataDriven5" fullname="PimsSupport.TESTS.LoginTest_Positive(&quot;chrome&quot;).ValidateLoginUsers_ExcelSource_DataDriven5" methodname="ValidateLoginUsers_ExcelSource_DataDriven5" classname="PimsSupport.TESTS.LoginTest_Positive" runstate="NotRunnable" seed="1488853953" result="Failed" label="Invalid" start-time="2021-06-06 13:07:59Z" end-time="2021-06-06 13:07:59Z" duration="0.000542" asserts="0">
              <properties>
                <property name="Description" value="Login validation using xml data source file for second row" />
                <property name="Category" value="Regression" />
                <property name="Category" value="SmokeTesting" />
                <property name="Order" value="6" />
                <property name="_SKIPREASON" value="System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation.&#xD;&#xA;  ----&gt; System.IO.FileNotFoundException : Could not find file 'C:\Users\CredentialsTest1.xlsx'." />
                <property name="_PROVIDERSTACKTRACE" value="   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)&#xD;&#xA;   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)&#xD;&#xA;   at System.Reflection.ConstructorInfo.Invoke(Object[] parameters)&#xD;&#xA;   at NUnit.Framework.Internal.Reflect.Construct(Type type) in D:\a\1\s\src\NUnitFramework\framework\Internal\Reflect.cs:line 140&#xD;&#xA;   at NUnit.Framework.Internal.Reflect.Construct(Type type, Object[] arguments) in D:\a\1\s\src\NUnitFramework\framework\Internal\Reflect.cs:line 155&#xD;&#xA;   at NUnit.Framework.TestCaseSourceAttribute.GetTestCaseSource(IMethodInfo method) in D:\a\1\s\src\NUnitFramework\framework\Attributes\TestCaseSourceAttribute.cs:line 252&#xD;&#xA;   at NUnit.Framework.TestCaseSourceAttribute.GetTestCasesFor(IMethodInfo method) in D:\a\1\s\src\NUnitFramework\framework\Attributes\TestCaseSourceAttribute.cs:line 170&#xD;&#xA;--FileNotFoundException&#xD;&#xA;   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)&#xD;&#xA;   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)&#xD;&#xA;   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)&#xD;&#xA;   at System.IO.File.Open(String path, FileMode mode, FileAccess access, FileShare share)&#xD;&#xA;   at FrameworkCore.Utilities.ExcelOperations2.ExcelToDataTable(String fileURL, String SheetName) in C:\Users\OTurkakin\source\Workspaces\FRAMEWORK\Project_XYZ\FrameworkCore\Utilities\ExcelOperations2.cs:line 19&#xD;&#xA;   at FrameworkCore.Utilities.ExcelOperations2.PopulateInColection(String fileURL, String SheetName) in C:\Users\OTurkakin\source\Workspaces\FRAMEWORK\Project_XYZ\FrameworkCore\Utilities\ExcelOperations2.cs:line 63&#xD;&#xA;   at FrameworkCore.DataFiles.ExelLoginTestDataAttributes1.InitializeElements(String fileSource, String sheetName, Int32 rowsToRun) in C:\Users\OTurkakin\source\Workspaces\FRAMEWORK\Project_XYZ\FrameworkCore\DataFiles\ExelLoginTestDataAttributes1.cs:line 26&#xD;&#xA;   at FrameworkCore.DataFiles.ExelLoginTestDataAttributes1..ctor() in C:\Users\OTurkakin\source\Workspaces\FRAMEWORK\Project_XYZ\FrameworkCore\DataFiles\ExelLoginTestDataAttributes1.cs:line 17" />
              </properties>
              <failure>
                <message><![CDATA[System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation.
  ----> System.IO.FileNotFoundException : Could not find file 'C:\Users\CredentialsTest1.xlsx'.]]></message>
                <stack-trace><![CDATA[   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.ConstructorInfo.Invoke(Object[] parameters)
   at NUnit.Framework.Internal.Reflect.Construct(Type type) in D:\a\1\s\src\NUnitFramework\framework\Internal\Reflect.cs:line 140
   at NUnit.Framework.Internal.Reflect.Construct(Type type, Object[] arguments) in D:\a\1\s\src\NUnitFramework\framework\Internal\Reflect.cs:line 155
   at NUnit.Framework.TestCaseSourceAttribute.GetTestCaseSource(IMethodInfo method) in D:\a\1\s\src\NUnitFramework\framework\Attributes\TestCaseSourceAttribute.cs:line 252
   at NUnit.Framework.TestCaseSourceAttribute.GetTestCasesFor(IMethodInfo method) in D:\a\1\s\src\NUnitFramework\framework\Attributes\TestCaseSourceAttribute.cs:line 170
--FileNotFoundException
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.Open(String path, FileMode mode, FileAccess access, FileShare share)
   at FrameworkCore.Utilities.ExcelOperations2.ExcelToDataTable(String fileURL, String SheetName) in C:\Users\OTurkakin\source\Workspaces\FRAMEWORK\Project_XYZ\FrameworkCore\Utilities\ExcelOperations2.cs:line 19
   at FrameworkCore.Utilities.ExcelOperations2.PopulateInColection(String fileURL, String SheetName) in C:\Users\OTurkakin\source\Workspaces\FRAMEWORK\Project_XYZ\FrameworkCore\Utilities\ExcelOperations2.cs:line 63
   at FrameworkCore.DataFiles.ExelLoginTestDataAttributes1.InitializeElements(String fileSource, String sheetName, Int32 rowsToRun) in C:\Users\OTurkakin\source\Workspaces\FRAMEWORK\Project_XYZ\FrameworkCore\DataFiles\ExelLoginTestDataAttributes1.cs:line 26
   at FrameworkCore.DataFiles.ExelLoginTestDataAttributes1..ctor() in C:\Users\OTurkakin\source\Workspaces\FRAMEWORK\Project_XYZ\FrameworkCore\DataFiles\ExelLoginTestDataAttributes1.cs:line 17]]></stack-trace>
              </failure>
            </test-case>
          </test-suite>
          <test-case id="0-1029" name="ValidateLoginUser_xmlSource_DataDriven6" fullname="PimsSupport.TESTS.LoginTest_Positive(&quot;chrome&quot;).ValidateLoginUser_xmlSource_DataDriven6" methodname="ValidateLoginUser_xmlSource_DataDriven6" classname="PimsSupport.TESTS.LoginTest_Positive" runstate="Runnable" seed="561994152" result="Failed" label="Error" start-time="2021-06-06 13:07:59Z" end-time="2021-06-06 13:08:26Z" duration="27.228807" asserts="0">
            <properties>
              <property name="Description" value="Login as a USER1 and validate landingPage URL is loded" />
              <property name="Category" value="Regression" />
              <property name="Category" value="SmokeTesting" />
              <property name="Order" value="7" />
            </properties>
            <failure>
              <message><![CDATA[OpenQA.Selenium.Support.UI.LoadableComponentException : Exception of type 'OpenQA.Selenium.Support.UI.LoadableComponentException' was thrown.
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.]]></message>
              <stack-trace><![CDATA[   at OpenQA.Selenium.Support.UI.LoadableComponent`1.Load()
   at PimsSupport.TESTS.LoginTest_Positive.SetUp() in C:\Users\OTurkakin\source\Workspaces\FRAMEWORK\Project_XYZ\PimsSupport\TESTS\Login\LoginTest_Positive.cs:line 29
--TearDown
   at PimsSupport.TESTS.LoginTest_Positive.Logout() in C:\Users\OTurkakin\source\Workspaces\FRAMEWORK\Project_XYZ\PimsSupport\TESTS\Login\LoginTest_Positive.cs:line 157]]></stack-trace>
            </failure>
          </test-case>
        </test-suite>
        <test-suite type="TestFixture" id="0-1030" name="RelationshipsTest(&quot;chrome&quot;)" fullname="PimsSupport.TESTS.RelationshipsTest(&quot;chrome&quot;)" classname="PimsSupport.TESTS.RelationshipsTest" runstate="Runnable" testcasecount="2" result="Failed" site="Child" start-time="2021-06-06 13:08:32Z" end-time="2021-06-06 13:09:34Z" duration="61.511640" total="2" passed="0" failed="2" warnings="0" inconclusive="0" skipped="0" asserts="0">
          <failure>
            <message><![CDATA[One or more child tests had errors]]></message>
          </failure>
          <test-case id="0-1031" name="Relationships_708A" fullname="PimsSupport.TESTS.RelationshipsTest(&quot;chrome&quot;).Relationships_708A" methodname="Relationships_708A" classname="PimsSupport.TESTS.RelationshipsTest" runstate="Runnable" seed="727943743" result="Failed" label="Error" start-time="2021-06-06 13:08:32Z" end-time="2021-06-06 13:09:00Z" duration="28.003620" asserts="0">
            <properties>
              <property name="Description" value="TC708A : Pims &gt; Relationships: Validate that url, page title, page footer, web table columns are enabled" />
              <property name="Category" value="Regression" />
              <property name="Order" value="1" />
            </properties>
            <failure>
              <message><![CDATA[OpenQA.Selenium.Support.UI.LoadableComponentException : Exception of type 'OpenQA.Selenium.Support.UI.LoadableComponentException' was thrown.
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.]]></message>
              <stack-trace><![CDATA[   at OpenQA.Selenium.Support.UI.LoadableComponent`1.Load()
   at PimsSupport.TESTS.RelationshipsTest.SetUp() in C:\Users\OTurkakin\source\Workspaces\FRAMEWORK\Project_XYZ\PimsSupport\TESTS\PIMS\Relationships\RelationshipsTest.cs:line 41
--TearDown
   at PimsSupport.TESTS.RelationshipsTest.LogoutCenterPoint() in C:\Users\OTurkakin\source\Workspaces\FRAMEWORK\Project_XYZ\PimsSupport\TESTS\PIMS\Relationships\RelationshipsTest.cs:line 122]]></stack-trace>
            </failure>
          </test-case>
          <test-case id="0-1032" name="Relationships_742" fullname="PimsSupport.TESTS.RelationshipsTest(&quot;chrome&quot;).Relationships_742" methodname="Relationships_742" classname="PimsSupport.TESTS.RelationshipsTest" runstate="Runnable" seed="1493058411" result="Failed" label="Error" start-time="2021-06-06 13:09:00Z" end-time="2021-06-06 13:09:27Z" duration="27.045105" asserts="0">
            <properties>
              <property name="Description" value="TC742 : Pims &gt; Relationships &gt; View &gt; Rates: Details" />
              <property name="Category" value="Regression" />
              <property name="Order" value="10" />
            </properties>
            <failure>
              <message><![CDATA[OpenQA.Selenium.Support.UI.LoadableComponentException : Exception of type 'OpenQA.Selenium.Support.UI.LoadableComponentException' was thrown.
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.]]></message>
              <stack-trace><![CDATA[   at OpenQA.Selenium.Support.UI.LoadableComponent`1.Load()
   at PimsSupport.TESTS.RelationshipsTest.SetUp() in C:\Users\OTurkakin\source\Workspaces\FRAMEWORK\Project_XYZ\PimsSupport\TESTS\PIMS\Relationships\RelationshipsTest.cs:line 41
--TearDown
   at PimsSupport.TESTS.RelationshipsTest.LogoutCenterPoint() in C:\Users\OTurkakin\source\Workspaces\FRAMEWORK\Project_XYZ\PimsSupport\TESTS\PIMS\Relationships\RelationshipsTest.cs:line 122]]></stack-trace>
            </failure>
          </test-case>
        </test-suite>
      </test-suite>
    </test-suite>
  </test-suite>
</test-run>